ENV_REPLACE_ME/diff-SERVICE_REPLACE_ME:
  stage: DIFF_STAGE
  <<: *ENV_REPLACE_ME_diff_template
  variables:
    PROJECT: SERVICE_REPLACE_ME
    K8S_NAMESPACES: NAMESPACE_REPLACE_ME
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner-deploy

ENV_REPLACE_ME/deploy-SERVICE_REPLACE_ME:
  stage: DEPLOY_STAGE
  needs: ["ENV_REPLACE_ME/diff-SERVICE_REPLACE_ME"]
  <<: *ENV_REPLACE_ME_deploy_template
  variables:
    PROJECT: SERVICE_REPLACE_ME
    K8S_NAMESPACES: NAMESPACE_REPLACE_ME
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner-deploy
