.yaml/build-config-for-jobs:
  stage: build-config-for-dev-jobs
  image: alpine:latest
  script:
    - apk add --no-cache bash
    - |
      cat ${BASE_TEMPLATE} > generated-${ENV_SLUG}-config.yml
      sed -i "s/ENV_REPLACE_ME/${ENV_SLUG}/g" generated-${ENV_SLUG}-config.yml
      sed -i "s/SERVICE_REPLACE_ME/grafana-lgmt-proxy/g" generated-${ENV_SLUG}-config.yml
      sed -i "s/NAMESPACE_REPLACE_ME/observability/g" generated-${ENV_SLUG}-config.yml
      sed -i "s/DIFF_STAGE/pre-deploy-${ENV_SLUG}/g" generated-${ENV_SLUG}-config.yml
      sed -i "s/DEPLOY_STAGE/deploy-${ENV_SLUG}/g" generated-${ENV_SLUG}-config.yml
    - cat generated-${ENV_SLUG}-config.yml

.yaml/trigger-dynamic-pipeline:
  stage: trigger-child-pipeline
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
